config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',               to: 'static_pages#help'
  get    '/terms',              to: 'static_pages#terms'
  get    '/privacy',            to: 'static_pages#privacy'
  get    '/about',              to: 'static_pages#about'
  get    '/contact',            to: 'static_pages#contact'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  get    '/favorites/index'
  post   '/favorites/:topic_id', to: 'favorites#favorite', as: 'favorite'
  delete '/favorites/:topic_id', to: 'favorites#unfavorite', as: 'unfavorite'
  get    '/uploads/create'
  get    '/uploads/destroy'


  resources :users
  resources :topics do
    collection do
      post 'confirm'
    end
    
    member do
      patch 'edit_confirm'
    end
    
    resources :comments
  end
  
  resources :words do
    collection do
      post 'confirm'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :uploads,             only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def terms
  end
  
  def privacy
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_footer.html.erb
<footer>
    <div class="container-fluid padding">
    <div class="row text-center bg-dark text-white">
      <div class="col-md-4">
        <hr color="white">
        <h5>Function</h5>
        <hr color="white">
          <h6><%= link_to "辞書", words_path %></h6>
          <h6><%= link_to "ユーザー索引", users_path %></h6>
      </div>

      <div class="col-md-4">
        <hr color="white">
        <h5>About</h5>
        <hr color="white">
          <h6><%= link_to "利用規約", terms_path %></h6>
          <h6><%= link_to "プライバシーポリシー", privacy_path %></h6>
      </div>

      <div class="col-md-4">
          <hr color="white">
          <h5>Web Author</h5>
          <hr color="white">
          <a class="twitter-timeline" href="https://twitter.com/Serori69938709?ref_src=twsrc%5Etfw">Tweets by Serori69938709</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>

      <div class="col-12">
        <hr color="white">
        <h6>&copy; Bio Topics,Designed by Tatsuya Yagi</h6>
      </div>
      
    </div>
  </div>
</footer>

app/views/static_pages/_form.html.erb
<div id="logreg-forms">
  <form class="form-signin">
      <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign in</h1>
      <div class="social-login">
          <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign in with Facebook</span> </button>
          <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign in with Google+</span> </button>
      </div>
      <p style="text-align:center">OR</p>
      <div class="input-group">
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
      </div>

      <div class="input-group">
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
      </div>

      <div class="input-group">
        <button class="btn btn-md btn-rounded btn-block form-control submit" type="submit"><i class="fas fa-sign-in-alt"></i> Sign in</button>
      </div>
      
      <hr>
      <button class="btn btn-primary btn-block" type="button" id="btn-signup"><i class="fas fa-user-plus"></i> Sign up New Account</button>
      </form>

  <form action="#" class="form-reset">
      <input type="email" id="resetEmail" class="form-control" placeholder="Email address" required="" autofocus="">
      <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
      <a href="#" id="cancel_reset"><i class="fas fa-angle-left"></i> Back</a>
  </form>

  <form action="#" class="form-signup">
      <div class="social-login">
        <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign up with Facebook</span> </button>
      </div>
      <div class="social-login">
        <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign up with Google+</span> </button>
      </div>
      <p style="text-align:center">OR</p>
      <input type="text" id="user-name" class="form-control" placeholder="Full name" required="" autofocus="">
      <input type="email" id="user-email" class="form-control" placeholder="Email address" required autofocus="">
      <input type="password" id="user-pass" class="form-control" placeholder="Password" required autofocus="">
      <input type="password" id="user-repeatpass" class="form-control" placeholder="Confirm Password" required autofocus="">
  </form>
</div>

app/views/static_pages/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to "BioTopics", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample04">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to topics_path, class: 'nav-link my-auto' do %>
            <i class="fas fa-newspaper article-icon"> 記事一覧</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to words_path, class: 'nav-link my-auto' do %>
            <i class="fas fa-book book-icon h6"> 辞書</i>
          <% end %>
        </li>
      </ul>
      <% if logged_in? %>
  　　<ul class="navbar-nav">
    　　  <li class="nav-item">
          <%= link_to "記事を投稿", new_topic_path, class: "btn btn-sm btn-primary ml-3 mb-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "辞書を作成", new_word_path, class: "btn btn-sm btn-primary ml-3 mb-1" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <div class="dropdown btn-group float-right">
          <a class="btn btn-default dropdown-toggle-menu-md-left" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= gravatar_for current_user, size:35 %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <%= link_to "プロフィール", current_user, class: "dropdown-item"  %>
            <%= link_to "ユーザー設定", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "お気に入り記事", favorites_index_path(current_user), class: "dropdown-item" %>
            <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item"  %>
          </div>
        </div>
      </ul>
      <% else %>
        <%= link_to "ユーザー登録", new_user_path, class: "btn btn-sm btn-light my-2 mr-3 " %>
        <%= link_to "ログイン", login_path, class: "btn btn-sm btn-primary my-2 " %>
      <% end %>
    </div>
  </nav>
</header>

app/views/static_pages/_signup_form.html.erb
<div id="logreg-forms">
  <form class="form-signin">
      <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign in</h1>
      <div class="social-login">
          <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign in with Facebook</span> </button>
          <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign in with Google+</span> </button>
      </div>
      <p style="text-align:center">OR</p>
      <div class="input-group">
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
      </div>

      <div class="input-group">
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
      </div>

      <div class="input-group">
        <button class="btn btn-md btn-rounded btn-block form-control submit" type="submit"><i class="fas fa-sign-in-alt"></i> Sign in</button>
      </div>
      
      <hr>
      <!-- <p>Don't have an account!</p>  -->
      <button class="btn btn-primary btn-block" type="button" id="btn-signup"><i class="fas fa-user-plus"></i> Sign up New Account</button>
      </form>

  <form action="#" class="form-reset">
      <input type="email" id="resetEmail" class="form-control" placeholder="Email address" required="" autofocus="">
      <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
      <a href="#" id="cancel_reset"><i class="fas fa-angle-left"></i> Back</a>
  </form>

  <form action="#" class="form-signup">
      <div class="social-login">
        <button class="btn facebook-btn social-btn" type="button"><span><i class="fab fa-facebook-f"></i> Sign up with Facebook</span> </button>
      </div>
      <div class="social-login">
        <button class="btn google-btn social-btn" type="button"><span><i class="fab fa-google-plus-g"></i> Sign up with Google+</span> </button>
      </div>
      <p style="text-align:center">OR</p>
      <input type="text" id="user-name" class="form-control" placeholder="Full name" required="" autofocus="">
      <input type="email" id="user-email" class="form-control" placeholder="Email address" required autofocus="">
      <input type="password" id="user-pass" class="form-control" placeholder="Password" required autofocus="">
      <input type="password" id="user-repeatpass" class="form-control" placeholder="Confirm Password" required autofocus="">
  </form>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="jumbotron jumbotron-fluid m-0">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-sm-6 col-md-6">
        <h1 class="text-light">Hello Scholar! <i class="fas fa-graduation-cap fa-rotate-45"></i></h1>
        <p class="text-light">Biotopicsは、読者の皆さんが生物学に関する知識や関心を共有するための記事投稿サイトです。朝顔の観察日記から、読んだ論文から得た知見、実験の失敗談など 生物学に関連するもので記事であれば、なんでもありです。 是非、あなたの生物学の知見を皆さんへ共有してください；）</p>
      </div>
      <div class="col-sm-6 col-md-6">
        <%= render partial: 'shared/login_form' %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<div>
   　
</div>

<div class="container rounded bg-light border border-primary my-5">
  <div class="row">
    <div class="col-12">
      <h3 class="text-center">プライバシーポリシー</h3>
      <p>
        Bio Topics（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
      </p>
      
      <h4>第1条（個人情報）</h4>
      <p>
      「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。
      </p>
      
      <h4>第2条（個人情報の収集方法）</h4>
      <p>
        当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。
      </p>
      
      <h4>第3条（個人情報を収集・利用する目的）</h4>
      <p>
        当社が個人情報を収集・利用する目的は，以下のとおりです。
        
        当社サービスの提供・運営のため
        ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
        ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため
        メンテナンス，重要なお知らせなど必要に応じたご連絡のため
        利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
        ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
        有料サービスにおいて，ユーザーに利用料金を請求するため
        上記の利用目的に付随する目的
      </p>
      
      <h4>第4条（利用目的の変更）</h4>
      <p>
        当社は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
        利用目的の変更を行った場合には，変更後の目的について，当社所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。
      </p>
      
      <h4>第5条（個人情報の第三者提供）</h4>
      <p>
        当社は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
        人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
        公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
        国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
        予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき
        利用目的に第三者への提供を含むこと
        第三者に提供されるデータの項目
        第三者への提供の手段または方法
        本人の求めに応じて個人情報の第三者への提供を停止すること
        本人の求めを受け付ける方法
        前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
        当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
        合併その他の事由による事業の承継に伴って個人情報が提供される場合
        個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合
      </p>
      
      <h4>第6条（個人情報の開示）</h4>
      <p>
        当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。
        本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合
        当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合
        その他法令に違反することとなる場合
        前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。
      </p>
      
      <h4>第7条（個人情報の訂正および削除）</h4>
      <p>
        ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
        当社は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
        当社は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。
      </p>
      
      <h4>第8条（個人情報の利用停止等）</h4>
      <p>
        当社は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
        前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
        当社は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
        前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
      </p>
      
      <h4>第9条（プライバシーポリシーの変更）</h4>
      <p>
        本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
        当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
      </p>
      
      <h4>第10条（お問い合わせ窓口）</h4>
      <p>
        本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。
        Eメールアドレス：vividcolor0121@me.com
      </p>
    </div>
  </div>
</div>