config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',               to: 'static_pages#help'
  get    '/terms',              to: 'static_pages#terms'
  get    '/privacy',            to: 'static_pages#privacy'
  get    '/about',              to: 'static_pages#about'
  get    '/contact',            to: 'static_pages#contact'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  get    '/favorites/index'
  post   '/favorites/:topic_id', to: 'favorites#favorite', as: 'favorite'
  delete '/favorites/:topic_id', to: 'favorites#unfavorite', as: 'unfavorite'
  get    '/uploads/create'
  get    '/uploads/destroy'


  resources :users
  resources :topics do
    collection do
      post 'confirm'
    end
    
    member do
      patch 'edit_confirm'
    end
    
    resources :comments
  end
  
  resources :words do
    collection do
      post 'confirm'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :uploads,             only: [:create, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic, counter_cache: :favorites_count
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def set_up
    @topic = Topic.find(params[:topic_id])
    @id_name = "#favorite-link-#{@topic.id}"
  end

  def index
    @favorite_topics = current_user.favorite_topics
    @favorite_topics =  @favorite_topics.paginate(page: params[:page])
  end
  
  def favorite
    @topic = Topic.find(params[:topic_id])
    favorite = current_user.favorites.new(topic_id: @topic.id)
    favorite.save
    redirect_to @topic
  end
  
  def unfavorite
    @topic = Topic.find(params[:topic_id])
    favorite = current_user.favorites.find_by(topic_id: @topic.id)
    favorite.destroy
    redirect_to @topic
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if logged_in? %>
  <% unless @topic.user_id==current_user.id %>
    <div class="favotite-link mt-3 mx-auto text-center" id="favorite-link-<%= @topic.id %>">
      <% if current_user.favorites.find_by(topic_id: @topic.id) %>
        <%= link_to unfavorite_path(@topic.id), method: :delete, remote: true do %>
            <div class = "favorite__button">いいね解除❤️<%= topic.favorites.count %></div>
        <% end %>
      <% else %>
        <%= link_to favorite_path(topic_id:@topic.id), method: :post, remote: true do %>
            <div class = "favorite__button">いいね（お気に入り）！♡️<%= topic.favorites.count %></div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/favorites/favorite.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("favorites/favorite", topic: @topic  )) %>');

app/views/favorites/index.html.erb
<% provide(:title, 'お気に入り記事') %>

<div class="container border border-dark favorite-topic">
  <div class="row">
    <div class="col-md-12 p-0">
      <h5 class="text-center text-light bg-dark"><%= current_user.name %>さんのお気に入り記事</h5>
    </div>
  </div>
  <div class="row">
      <div class="col-md-12 m-3 mx-auto">
        <%= will_paginate @favorite_topics,renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
        <% @favorite_topics.each do |topic| %>
        <div class="row topics bg-light">
          <div class="col-1 mx-auto p-0">
            <%= link_to gravatar_for(topic.user, size: 50), topic.user %>
          </div>
          <div class="col-11 mx-auto">
            <%= link_to topic.title, topic_path(topic.id) %>
            <h6><%= time_ago_in_words(topic.created_at) %> ago.</h6>
          </div>
        </div>
        <% end %>
        <%= will_paginate @favorite_topics,renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
  </div>
</div>

app/views/favorites/unfavorite.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("favorites/favorite", topic: @topic  )) %>');