config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',               to: 'static_pages#help'
  get    '/terms',              to: 'static_pages#terms'
  get    '/privacy',            to: 'static_pages#privacy'
  get    '/about',              to: 'static_pages#about'
  get    '/contact',            to: 'static_pages#contact'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  get    '/favorites/index'
  post   '/favorites/:topic_id', to: 'favorites#favorite', as: 'favorite'
  delete '/favorites/:topic_id', to: 'favorites#unfavorite', as: 'unfavorite'
  get    '/uploads/create'
  get    '/uploads/destroy'


  resources :users
  resources :topics do
    collection do
      post 'confirm'
    end
    
    member do
      patch 'edit_confirm'
    end
    
    resources :comments
  end
  
  resources :words do
    collection do
      post 'confirm'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :uploads,             only: [:create, :destroy]
end

app/models/topic.rb
class Topic < ApplicationRecord
  acts_as_taggable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: :user
  
  # 直接SQLを引数として与える:desc
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
  validates :title,   presence: true
  
  def favorite(user)
    favorites.create(user_id: user.id)
  end
  
  def unfavorite(user)
     favorites.find_by(user_id: user.id).destroy
  end
  
  def favorite?(user)
    favorite_users.include?(user)
  end
  
  def self.search(search)
    if search
      where(['content LIKE ?', "%#{search}%"])
    else
      all
    end
  end
  
  def self.content_intro
    @topic = Topic.find(params[:id])
    @topic.content[0..10]
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.includes(:favorite_users).search(params[:search]).paginate(page: params[:page], per_page: 10)
    @all_ranks = Topic.find(Favorite.group(:topic_id).order('count(topic_id) desc').limit(10).pluck(:topic_id))
    
    if params[:tag_name]
      @topics = @topics.tagged_with("#{params[:tag_name]}")
    end
  end

  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    if params[:back]
      render :new
    elsif @topic.save
      redirect_to @topic
      flash[:info] = "記事が投稿されました。"
    else
      render :new
    end
  end
  
  def confirm
    @topic = current_user.topics.new(topic_params)
    render :new if @topic.invalid?
  end
  
  def edit_confirm
    @topic = Topic.find(params[:id])
    @topic.update(topic_params)
  end
  
  def show
    @topic = Topic.find(params[:id])
    @comment = Comment.new
    @comments = @topic.comments
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def update
    @topic = Topic.find(params[:id])
    @topic.update(topic_params)
    flash[:success] = "記事は編集されました"
    redirect_to @topic
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    
    if current_user.id == @topic.user_id
      @topic.destroy
      flash[:success] = "記事は削除されました"
      redirect_to topics_path
    else
      redirect_to @topic
      flash[:danger] = "記事は作成者以外消せません。"
    end
  end
  
  private

  def topic_params
    params.require(:topic).permit(:title, :content, :tag_list)
  end
  
  def correct_user
    @topic = current_user.topic.find_by(id: params[:id])
    redirect_to current_user if @topic.nil?
  end
  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_all_topics.html.erb
<div class="container-fluid mx-auto"> 
  <div class="row mx-3 my-3">
    <div class="col-md-8 col-sm-12 mx-auto p-0">
      <% if params[:tag_name] %>
        <div class="alert alert-info">"タグ：<%= params[:tag_name] %>" で絞り込み中</div>
      <% end %>
      <%= will_paginate @topics,renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      <% @topics.each do |topic| %>
      <div class="row topics bg-light mx-3">
        <div class="col-1 mx-auto p-0">
          <%= link_to gravatar_for(topic.user, size: 50), topic.user %>
        </div>
        <div class="col-11 mx-auto">
          <%= link_to topic.title, topic_path(topic.id) %>
          <% if topic.favorite_users.count > 0 %>
          <div class="d-inline">
            ❤️<%=topic.favorite_users.count %>
          </div>
          <% end %>
          <h6><%= time_ago_in_words(topic.created_at) %>前に作成</h6>
        </div>
      </div>
        <% end %>
        <%= will_paginate @topics,renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    </div>
    <% unless params[:tag_name] %>
    　<%= render partial:"iine_ranking" %>
    <% end %>
  </div>
</div>

app/views/topics/_author_function.html.erb
<% if logged_in? %>
  <% if current_user.id == @topic.user_id %>
    <%= link_to edit_topic_path do %>
      <i class="far fa-edit btn btn-outline-light mx-2"> 編集</i>
    <% end %>
    <%= link_to @topic, method: :delete, data: {confirm: "投稿記事を削除しますか？", cancel: "キャンセル", commit: "削除する", title: "削除の確認"} do%>
      <i class="fas fa-eraser btn btn-outline-light "> 削除</i>
    <% end %>
  <% end %>
<% end %>

app/views/topics/_iine_ranking.html.erb
<div class="col-md-3 col-sm-12 mx-auto">
  <div class="iine-ranking bg-light rounded-top pb-1">
  <h5 class="text-center bg-warning rounded py-3">
    <i class="fas fa-crown">
    　注目の記事　
    </i>
    <i class="fas fa-crown"></i>
  </h5>
  <% @all_ranks.each do |topic| %>
  <div class="row topics mx-3">
    <div class="col-2 p-0">
      <%= link_to gravatar_for(topic.user, size: 50), topic.user %>
    </div>
    <div class="col-9 mr-1">
      <%= link_to topic.title, topic_path(topic.id) %>
      <% if topic.favorite_users.count > 0 %>
      <div class="d-inline">
        ❤️<%=topic.favorite_users.count %>
      </div>
      <% end %>
      <h6><%= time_ago_in_words(topic.created_at) %>前に作成</h6>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/topics/_post_form.html.erb
<div class="row">
  <div class="col-12 mt-3">
    <%= f.label :title, '投稿タイトル' %>
    <%= f.text_field :title, class: 'form-control', style: "width: 100 %" %>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    <%= f.label :tag_list, 'タグ(カンマ区切りで任意のタグを付加できます）' %>
    <%= f.text_field :tag_list, value: @topic.tag_list.join(','), class: "form-control", "data-role" => "tagsinput" %>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    <%= f.label :content, '記事内容'  %>
    <%= f.text_area :content, 'data-provider': :summernote %>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    <%= f.submit '確認画面へ', class: 'btn btn-info btn-block' %>
    <%= hidden_field_tag :user_id, current_user.id %>
  </div>
</div>

app/views/topics/_topic.html.erb
<div class="container">
  <div class="row topics bg-light">
    <div class="col-1 mx-auto">
      <%= link_to gravatar_for(topic.user, size: 50), topic.user %>
    </div>
    <div class="col-11 mx-auto">
      <%= link_to topic.title, topic_path(topic.id) %>
      <h6><%= time_ago_in_words(topic.created_at) %>前に作成</h6>
    </div>
  </div>
</div>

app/views/topics/confirm.html.erb
<div class="conatiner">
  <div class="row">
    <h5 class="col mt-5 text-center">以下の内容で記事を投稿しますか？</h5>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5 bg-dark text-white">
      
    <%= form_for @topic do |f| %>
      <h4>
      <%= @topic.title %>
      <%= f.hidden_field :title %>
      </h4>
      <% @topic.tag_list.each do |tag| %>
      　<%= f.hidden_field :tag_list, value: @topic.tag_list.join(',') %>
        <span class="badge badge-primary"><%= tag %></span>
      <% end %>
    </div>
    <div class="col-md-12 bg-white">
      <%== @topic.content %>
      <%= f.hidden_field :content %>
    </div>
    <div class="col-md-12 bg-dark text-white">
      <h5>by <%= @topic.user.name %></h5>
      
      
    </div>
    <div class="mx-auto m-3">
      <%= f.submit '投稿する', class: "btn btn-primary" %>
      <%= f.submit '修正', name: "back",class: "btn btn-default" %>
    </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<% provide(:title, '記事編集') %>

<div class="container">
  <div class="row">
     <div class="col mt-5 bg-dark py-2 rounded">
     <h2 class="d-inline text-light"><i class="fas fa-pencil-alt"> 記事編集</i></h2>
     <%= link_to '記事一覧', topics_path, class: 'btn btn-outline-info d-inline float-right' %>
     </div>
  </div>
    <%= form_for @topic, url: {action: 'edit_confirm'} do |f|  %>
      <%= render partial: "post_form", locals: { f: f } %>　
    <% end %>
    </div>
  </div>
</div>

app/views/topics/edit_confirm.html.erb
<div class="conatiner">
  <div class="row">
    <h5 class="col mt-5 text-center">以下の内容で記事を編集しますか？</h5>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-5 bg-dark text-white">
      
    <%= form_for @topic do |f| %>
      <h4>
      <%= @topic.title %>
      <%= f.hidden_field :title %>
      </h4>
      <% @topic.tag_list.each do |tag| %>
      　<%= f.hidden_field :tag_list, value: @topic.tag_list.join(',') %>
        <span class="badge badge-primary"><%= tag %></span>
      <% end %>
    </div>
    <div class="col-md-12 bg-white">
      <%== @topic.content %>
      <%= f.hidden_field :content %>
    </div>
    <div class="col-md-12 bg-dark text-white">
      <h5>by <%= @topic.user.name %></h5>
    </div>
    <div class="mx-auto m-3">
      <%= f.submit '編集する', class: "btn btn-primary" %>
      <%= f.submit '修正', name: "back",class: "btn btn-default" %>
    </div>
    <% end %>
  </div>

app/views/topics/index.html.erb
<% provide(:title, "記事一覧") %>

<div class="container-fluid mt-5">
  <div class="row mx-3">
    <div class="col-md-12 mt-3 p-0 ">
    <h4 class="text-center text-light bg-dark py-3 rounded"><i class="fas fa-search"></i>記事検索</h4>
    <%= form_tag(yield(:path), method: :get) do %>
      <%= text_field_tag :search, params[:search], class:"form-control", placeholder:"キーワードを入力してください"  %>
      <%= submit_tag '検索',class:"btn btn-primary btn-block mt-1" %>
    <% end %>
    </div>
  </div>
</div>

<%= render 'all_topics' %>

app/views/topics/new.html.erb
<% provide(:title, '記事投稿') %>

<div class="container">
  <div class="row">
     <div class="col mt-5 bg-dark py-2 rounded">
     <h2 class="d-inline text-light"><i class="fas fa-pencil-alt"> 記事投稿</i></h2>
     <%= link_to '記事一覧', topics_path, class: 'btn btn-info d-inline float-right' %>
     </div>
  </div>
    <%= form_for @topic, url: {action: 'confirm'} do |f|  %>
      <%= render partial: "post_form", locals: { f: f } %>　　
    <% end %>
</div>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-3 py-3 bg-dark text-white ">
      <h4 class="d-inline">
        <%= @topic.title %>
        <%= render partial: "author_function" %>
      </h4>
      <div >
      タグ：
      <% @topic.tag_list.each do |tag| %>
        <span class="badge badge-primary mt-3"><%= link_to tag, topics_path(tag_name: tag), class: "text-white" %></span>
      <% end %>
      </div>
    </div>
    <div class="col-md-12 bg-white">
      <%== @topic.content %>
    </div>
    <div class="col-md-12 py-3 bg-dark text-white ">
      <h5>記事作成者： <%= link_to @topic.user.name, user_path(id: @topic.user_id) %></h5>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
    <%= render 'favorites/favorite', topic: @topic %>
    </div>
  </div>
</div>

<div class="container bg-light my-3 py-3">
  <div class="row">
    <div class="col-12">
      <div id="comments_area">
        <% if @comments.any? %>
          <%= render partial: 'comments/index', locals: { comments: @comments } %>
        <% else %>
          <h5 class="text-center">まだコメントはありません…</h5>
        <% end %>
      </div> 
    </div>
    <div class="col-12">
      <% if logged_in? %>
        <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
      <% end %>
    </div>
  </div>
</div>