config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/help',               to: 'static_pages#help'
  get    '/terms',              to: 'static_pages#terms'
  get    '/privacy',            to: 'static_pages#privacy'
  get    '/about',              to: 'static_pages#about'
  get    '/contact',            to: 'static_pages#contact'
  get    '/login',              to: 'sessions#new'
  post   '/login',              to: 'sessions#create'
  delete '/logout',             to: 'sessions#destroy'
  get    '/favorites/index'
  post   '/favorites/:topic_id', to: 'favorites#favorite', as: 'favorite'
  delete '/favorites/:topic_id', to: 'favorites#unfavorite', as: 'unfavorite'
  get    '/uploads/create'
  get    '/uploads/destroy'


  resources :users
  resources :topics do
    collection do
      post 'confirm'
    end
    
    member do
      patch 'edit_confirm'
    end
    
    resources :comments
  end
  
  resources :words do
    collection do
      post 'confirm'
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :uploads,             only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger text-center">
      <h4><%= model.errors.count %>件のエラーがあります。</h4>
    </div>
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login_form.html.erb
<div id="logreg-forms">
  <h1 class="h3 font-weight-normal text-center">ログイン</h1>
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.email_field :email,class: "form-control mb-1", placeholder: "メールアドレス" %>
      <%= f.password_field :password,class: "form-control mb-1", placeholder: "パスワード" %>
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>ログイン情報を記憶しますか？</span>
      <% end %>
      <%= f.submit "ログイン", class: "btn btn-md btn-rounded btn-block form-control submit" %>
    <% end %>
    <div class="my-3">
      <%= link_to new_user_path, class: "btn btn-success btn-sm mx-5 my-2" do %>
        <h6 class="text-center"><i class="far fa-user">ユーザー登録がまだの場合</i></h6>
      <% end %>
      <%= link_to new_password_reset_path, class: "btn btn btn-danger btn-sm mx-5 my-2" do %>
        <h6 class="text-center"><i class="far fa-dizzy">パスワードを忘れてしまった場合</i></h6>
      <% end %>
    </div>
</div>